### ISSUE TITLE
Flip Doesn’t Work Second time with initialState.

### ISSUE THREAD

**Issue by fazal-e-majid** [qchenqizhi/QCropper#9]
@qchenqizhi  Thank you for this beautiful library. I’m facing a bug that when I just flip the image and click done. and then when I come back with initial state and again change just flip, this time it’s not allowing me to click done. 
Is there no any support for flip in state management ?

**Comment by qchenqizhi** [comment]
Thank you for your feedback, this is a bug and has been fixed. [Update state when flipping](https://github.com/qchenqizhi/QCropper/commit/d2839596df18da8ad291661b9cd4621d8dbc7970)

**Comment by fazal-e-majid** [comment]
@qchenqizhi Thank you for fixing one part of the issue. Although the flip is working good independently but the bug is still there. The reset button has no effect on flip. And there is a case where Done button doesn’t work:
1. Reset Button is not in sync with flip.
2. Done button doesn’t work with flip. Possible steps to reproduce are :
-> Change only `flip`.
-> `Done`.
-> Next time just click `Reset`. //( doesn’t resets flip ) => One.
-> `Done` doesn’t work either. // => Two.

**Comment by qchenqizhi** [comment]
@fazal-e-majid There should be no problem this time. 😅 [Reset the flip state when reset](https://github.com/qchenqizhi/QCropper/commit/d7ed6e62f30c5da7cbb4dcb6680ea3ff1404bf60)

**Comment by fazal-e-majid** [comment]
@qchenqizhi Thank you for creating this project and giving support ! ❤️

**Comment by fazal-e-majid** [comment]
@qchenqizhi there’s another case where it’s not working as expected.

-> Apply just `flip`.
-> `Cancel`.
-> `Reopen` the controller. // Image is already flipped.

**Comment by qchenqizhi** [comment]
@fazal-e-majid I cannot reproduce this problem, can you elaborate on the details of "Reopen"?

**Comment by qchenqizhi** [comment]
In addition, the current logic is: After `Cancel`, this `CropperViewController `needs to be discarded, so there is no reset work when `Cancel`. If you need to reopen it, you need to pass a `CropperState` to the `init(originalImage: initialState)` method of `CropperViewController`

**Comment by fazal-e-majid** [comment]
got you !
@qchenqizhi Thank you very much. ❤️❤️
